# Generated by Django 3.1 on 2020-09-17 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0002_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menus', to='ec.category', verbose_name='料理カテゴリ'),
        ),
    ]
