# Generated by Django 3.1.1 on 2020-09-20 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0005_choicelocation_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChoiceLocation',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
