# Generated by Django 3.1.1 on 2020-09-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0009_auto_20200920_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='soldout',
            field=models.IntegerField(blank=True, choices=[(0, '販売中'), (1, '売り切れ中')], max_length=10, null=True, verbose_name='販売状況'),
        ),
    ]
