# Generated by Django 3.1.1 on 2020-09-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0012_remove_menu_soldout'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='soldout',
            field=models.IntegerField(blank=True, choices=[(0, '通常販売'), (1, '売り切れ中')], null=True, verbose_name='販売状況'),
        ),
    ]
