# Generated by Django 3.1 on 2020-12-14 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0013_menu_soldout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicelocation',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ec.location', verbose_name='住所'),
        ),
    ]
