# Generated by Django 3.1 on 2020-12-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_form_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='product',
            field=models.CharField(default=2, max_length=255, verbose_name='注文商品'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='quantity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
