# Generated by Django 3.1 on 2020-12-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20201215_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='product',
        ),
        migrations.RemoveField(
            model_name='form',
            name='quantity',
        ),
    ]
