# Generated by Django 3.1 on 2020-12-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20201215_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='order_content',
            field=models.CharField(default=2, max_length=512, verbose_name='注文内容'),
            preserve_default=False,
        ),
    ]
