# Generated by Django 3.1 on 2020-12-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_form_order_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='myself',
            field=models.BooleanField(default=True),
        ),
    ]
