# Generated by Django 3.1 on 2021-02-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_form_myself'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='totalprice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
